name: leofinance_hive_api
description: A simple API for connecting to the Hive network.
version: 0.4.7
repository: https://github.com/LeoFinance/hive-api

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.3
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.2
  faker: ^2.0.0
  json_serializable: ^6.2.0
  mockito: ^5.1.0
  test: ^1.21.0
  very_good_analysis: ^2.4.0
